services:

  # PostgreSQL
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - web.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  # Backend Django
  backend:
    build: .
    command:
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate && 
      ./manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - web.env
    volumes:
      - .:/service

volumes:
  db:
    driver: local
